-- migrate:up

CREATE EXTENSION IF NOT EXISTS pg_trgm;
--We will not use IF NOT EXISTS for these items, because if we call them again, we would like the failure to be loud. 
CREATE TABLE compiled_records ( 
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  canonical_name  TEXT        NOT NULL,

    --The goal of this normalization is generate a trigram index for better fuzzy searching. 
normalized_name   TEXT        NOT NULL
                    GENERATED ALWAYS AS (
                      trim(regexp_replace(
                        regexp_replace(lower(
                          substring(canonical_name from '\$a([^$]*)')
                        ),
                        '([a-z])\.', '\1', 'g'),
                        '[^a-z0-9]+', ' ', 'g'
                      ))
                    ) STORED,


    first_word      TEXT        NOT NULL
                    GENERATED ALWAYS AS (
                      split_part(
                        trim(regexp_replace(
                          regexp_replace(lower(
                            substring(canonical_name from '\$a([^$]*)')
                          ),
                          '([a-z])\.', '\1', 'g'),
                          '[^a-z0-9]+', ' ', 'g'
                        )),
                        ' ', 1
                      )
                    ) STORED,

  identifier_a    SMALLINT    NOT NULL CHECK (identifier_a BETWEEN 100 AND 999),
  identifier_b    SMALLINT    NOT NULL CHECK (identifier_b BETWEEN 100 AND 999),

  date            DATE        NOT NULL, --This will come from the database, others will be generated by the system to track changes since this migration. 

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX compiled_records_first_word_idx
  ON compiled_records (first_word);

CREATE INDEX compiled_records_normalized_trgm_idx
  ON compiled_records USING GIN (normalized_name gin_trgm_ops);

-- migrate:down
DROP TABLE compiled_records;

DROP EXTENSION IF EXISTS pg_trgm;